# Generated by Django 4.1.2 on 2022-10-27 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0003_notif_delete_notifs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notif',
            name='recipient',
        ),
    ]
